kids-first/kf-ui-release-coordinator

src/views/Login.js
=> Style login

src/components/Nav.js, src/index.css, src/views/Status.js
=> 🎨 Add cards to status page

src/components/TaskList.js
=> 🐛 Fix task status api call

src/views/Service.js
=> ✨ Editable service

src/components/Events.js, src/components/TaskList.js, src/views/Release.js
=> Event formatting

src/components/Nav.js, src/components/ReleaseTable.js, src/components/ServiceList.js, src/components/StudyTable.js, src/containers/Root.js, src/forms/NewRelease.js, src/views/Release.js, src/views/Studies.js, src/views/Study.js
Adds release version numbers to the ui:
- Support for major releases
- Add studies view with latest versions
- Add versions to planner
- Add versions to release pages
=> ✨ Support for release versions

src/forms/NewRelease.js
Increases number of studies fetched from coordinator.
This should probably be taken care of using the pagination better, but should be sufficient for now.
=> 🔧 Increase number of studies shown for release

CHANGLOG.md, package.json
Feature Emojis: ✨x2 ♻️x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/feature) x2 [bug](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/bug) x1 [refactor](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/refactor) x1
- (#60) ✨ Add confirmation dialog for new releases - @dankolbman
- (#59) ♻️ Clean up table sorting - @dankolbman
- (#58) ✨ Allow tables to be sorted - @dankolbman
=> 🏷 Release 1.1.1

package.json, src/components/PublishHistory.js, src/views/Status.js, yarn.lock
Add new cards to the status dashboard.
=> ✨ Status rehash

.circleci/config.yml, README.md, src/components/PublishHistory.js, src/components/StudyTable.js, src/forms/NewRelease.js, src/utils/index.js, src/views/Status.js, src/views/Study.js
=> 🚨 Linting and CI

package.json, src/App.js, src/components/ReleaseTable.js, src/components/ServiceList.js, src/components/StudyTable.js, src/containers/Root.js, src/forms/NewRelease.js, src/forms/NewService.js, src/views/Planner.js, src/views/Profile.js, src/views/Release.js, src/views/Releases.js, src/views/Services.js, src/views/Status.js, src/views/Studies.js, src/views/Study.js, yarn.lock
First usable draft of the coordinator with the design system. More style refactoring is expected soon.
=> 🎨 Migration to Kids First design system

CHANGLOG.md
Feature Emojis: ✨x3 ♻️x1 🎨x1 🚨x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/feature) x4 [refactor](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/refactor) x3 [devops](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/devops) x1
- (#70) ✨ Add report summary to release page - @dankolbman
- (#81) ♻️ Add release description form to release page - @dankolbman
- (#80) 🎨 Migration to Kids First design system - @dankolbman
- (#69) ✨ Add release timeline to release pages - @dankolbman
- (#68) 🚨 Linting and CI - @dankolbman
- (#67) ✨ Status rehash - @dankolbman
=> 🏷 Release 1.2.0

package.json, yarn.lock
Uses production release `0.1.0` of the UI Kit.
=> ⬆️ Bump ui kit version

CHANGLOG.md, package.json
Feature Emojis: ⬆️x1 🎨x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/refactor) x1 [feature](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/feature) x1
- (#86) ⬆️ Bump ui kit version - @dankolbman
- (#85) 🎨 Add last published fields to study tables - @dankolbman
=> 🏷 Release 1.2.1

src/containers/Root.js, src/globalConfig.js
=> ✨Add banner indicating which environment you're in

src/forms/NewRelease.js
Shows all services regardless of whether they are enabled or not.
=> 🎨 Show all services in planner

src/forms/NewRelease.js
Fixes version sort on planner study tables
Increases size of study table in planner.
=> ♻️ Planner fixes

package.json, src/containers/HeaderContainer.js, src/containers/Root.js, src/index.js, src/views/Profile.js, yarn.lock
Persists state to local storage so that the user does not have to log in again.
=> ✨ Persist state

src/actions/auth.js, src/containers/Root.js, src/reducers/auth.js
Stores the expiration of the ego JWT so that the application knows to reauthenticate when hydrating from the localstorage.
=> ✨ Re-authenticate user if token is expired

src/forms/NewReleaseForm.js, src/reducers/index.js
Loads user for author field from state.
Uses select for `isMajor` field, could not get checkbox to properly change state.
=> 🐛 Fix release form

src/components/ReleaseReportSummary.js
Updates the reports endpoint to pull from `/reports/releases` on the release task service.
=> 🐛 Update release reports endpoint

src/actions/studies.js, src/containers/StudiesContainer.js, src/reducers/studies.js
Needed to syncronize studies in the coordinator with what exists in the dataservice.
=> ✨ Add syncronize button to sync coordinator with dataservice studies

src/components/ReleaseList.js
Naive filters that allow columns on the release table to be filtered down.
Fixes #110
=> ✨ Add colum filters to releases table

src/globalConfig.js, src/views/Release.js
Add button to download snapshot of the release from the snapshot service.
Fixes #109
=> ✨ Add button to download snapshot

CHANGLOG.md, package.json
Feature Emojis: ✨x2 🐛x1 🖼x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/feature) x2 [bug](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/bug) x1 [documentation](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/documentation) x1
- (#114) ✨ Add button to download snapshot - @dankolbman
- (#112) ✨ Add column filters to releases table - @dankolbman
- (#111) 🐛 Restore sort by SemVer to tables - @dankolbman
- (#108) 🖼 Update logo - @dankolbman
=> 🏷 Release 1.3.1

src/actions/auth.js, src/components/Events.js, src/components/MarkdownEditor.js, src/components/Nav.js, src/components/Progress.js, src/components/PublishHistory.js, src/components/ReleaseReportSummary.js, src/components/ReleaseTimeline.js, src/components/ServiceList.js, src/components/StatusBadge.js, src/components/StudiesTable.js, src/components/TaskList.js, src/components/Tasks.js, src/components/utils.js, src/forms/NewService.js, src/views/NewService.js, src/views/Profile.js, src/views/Release.js, src/views/Services.js, src/views/Status.js, src/views/Studies.js, src/views/Study.js
Applies prettier formatting to existing files.
=> 🚨 Apply prettier formatting

Dockerfile
Add argument `REACT_APP_AUTH0_REDIRECT_URI` to Dockerfile, enable pass redirect URI as an environment variable.
=> ♻️ Refactor docker setting by adding arg Auth0 Redirect URI

yarn.lock
Attempt to solve vulns by updating packages in yarn.lock.
=> ⬆️ Upgrade yarn deps

netlify.toml
We only allow https in our auth0 callbacks.
=> 🐛 Add protocol to redirect url

src/forms/NewService.js
Attaches user state to props.
Fixes #119
=> 🐛 Fix new service form

CHANGLOG.md, package.json
Integrates Auth0 and removes the ant design system entirely.
Feature Emojis: 🐛x3 🚨x3 🔧x2 ♻️x2 🔥x1 ⬆️x1 ✨x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/refactor) x6 [bug](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/bug) x4 [devops](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/devops) x1 [feature](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/feature) x1
- (#134) 🔥 Remove ant - @dankolbman
- (#133) 🐛 Fix new service form - @dankolbman
- (#132) 🐛 Fixes react-table selection - @dankolbman
- (#131) 🚨 Update to new prettier standard - @dankolbman
- (#130) 🐛 Add protocol to redirect url - @dankolbman
- (#129) ⬆️ Upgrade yarn deps - @dankolbman
- (#128) 🔧 Add …
=> 🏷 Release 1.4.0

src/views/Release.js
Allows a user to re-run a release with identical parameters.
=> ✨ Add re-run release button

.circleci/config.yml, package.json
Adds CI status check for bundle size.
=> 👷 Add bundlesize CI check

src/views/Login.js, src/views/Studies.js
Updates the login page to look the same as the data tracker.
=> 💄 Style login consistently with data tracker

src/containers/StudiesContainer.js, src/views/Releases.js, src/views/Services.js, src/views/Studies.js
Sets labelPosition on buttons to properly format the contained icons.
Uses Grid instead of float to align buttons to top right of page.
=> 💄 Properly use icon buttons

src/components/Events.js, src/components/LatestPublish.js, src/components/LatestReleases.js, src/components/ReleaseList.js, src/components/StudiesTable.js, src/components/TaskList.js, src/views/Release.js
Makes labels basic and turns them into buttons where appropriate.
=> ♻️ Simplify labels

CHANGLOG.md, package.json
Change to Semantic UI framework
Feature Emojis: 💄x3 ✨x2 ♻️x1 👷 x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/refactor) x5 [feature](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/feature) x2 [devops](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/devops) x1
- (#144) ♻️  Simplify labels - @dankolbman
- (#143) 💄 Properly use icon buttons - @dankolbman
- (#142) 💄 Style login consistently with data tracker - @dankolbman
- (#141) 💄 Style header consistently with data tracker - @dankolbman
- (#138) 👷 Add bundlesize CI check - @dankolbman
- (#140) ✨ Add re-run release button - @dankolbman
- (#139) ✨ Semantic ui - @dankolbman
=> 🏷 Release 1.5.0

package.json, src/components/ReleaseList.js, src/components/StudiesTable.js, src/containers/Releases.js, src/views/Releases.js, yarn.lock
Replaces tables with semantic table component.
Fixes #150 
Fixes #149
=> ♻️ Semantic tables

src/forms/NewService.js, src/views/NewService.js, src/views/Service.js
This updates the new service and edit existing service forms to be more user friendly and allow the user to modify the url of the service once it's been created.
=> 💄 Restyle service forms

.circleci/config.yml, package.json, public/index.html, src/components/Header.js, src/components/MarkdownEditor.js, src/components/Progress.js, src/components/ReleaseHeader.js, src/components/ReleaseList.js, src/queries.js, src/views/Release.js, yarn.lock
Re-styling for the release status page.
=> 💄 Release view refactor

src/views/NewService.js, src/views/Planner.js, src/views/Releases.js, src/views/Service.js, src/views/Services.js, src/views/Studies.js, src/views/Study.js
Removes cards as page layout tools and relies on segments instead.
=> 💄 Remove use of cards as layout elements

src/containers/StudiesContainer.js, src/views/Studies.js
Makes the sync studies button functional on the study list view and removes the sync button from the studies container when needed.
=> 🐛 Study sync

src/views/Planner.js, src/views/Releases.js, src/views/Services.js, src/views/Status.js, src/views/Studies.js
Adds unique page icons to headers and the status page.
=> 💄 Page icons

src/components/Progress.js, src/components/ServiceList.js, src/queries.js
Adds failed state to progress bar.
Adds health status to task service list.
=> 🐛 Correct missing values

src/components/TaskList.js, src/queries.js
Filters task list by release if a release id is provided.
=> 🐛 Filter task list by release

package.json, src/containers/HeaderContainer.js, src/globalConfig.js
Adds git hash and version to the app header.
=> ✨ Add git version and hash to header

src/components/Events.js, src/queries.js, src/views/Status.js
Re-styles event logs to be one line.
=> 💄 Restyle event logs

package.json, yarn.lock
Upgrades dependencies to avoid deprecation of some lifecycle methods in react.
=> ⬆️ Upgrade dependencies

src/queries.js, src/views/Service.js
Fixes missing fields in queries.
=> 🐛 Fix queries

package.json, src/containers/HeaderContainer.js, src/queries.js
Adds status of the coordinator api to the header and changes to use the describe version.
=> ✨ Add api status to header

src/components/Header.js, src/containers/HeaderContainer.js
Reloads the user menu in the navbar if the query for the current user came back after it has already rendered.
=> 🐛 Reload new profile sign-ins

src/App.css, src/components/MarkdownEditor.js, src/index.js, src/mutations.js, src/views/Release.js
REST API calls for updating releases are removed, instead, we call the GraphQL mutation. 
Fixed the case where it wasn't updating the description from the UI.
Closes #176
Closes #177
=> ✨ Use GraphQL mutation to update release description markdown

package.json, src/components/MarkdownEditor.js, src/components/ReleaseNotes.js, src/mutations.js, src/queries.js, src/views/Release.js, yarn.lock
Users are allowed to add / update / remove the release note. For each release we have one release note per study.
No notes:
Creating a new note:
Save/Displaying an existing note:
Editing an existing note:
Remove a note:
=> ✨ Add release notes component to release page

src/App.css, src/components/Header.js, src/components/MarkdownEditor.js, src/components/NoteItem.js, src/components/NotesList.js, src/components/StudyNote.js, src/components/utils.js, src/containers/Root.js, src/queries.js, src/views/ReleaseNotes.js
List out release with descriptions and notes
Click on the `Add/Edit` button to add/edit a note for a specific release and study
Click on the `Delete` button to remove a note from a specific release and study
When there is no published releases
=> ✨ Add release notes page listing out all published releases' notes

Jenkinsfile
Adds agent label to the Jenkins file to send jobs to the right worker queue.
=> 👷‍♂️ Add agent label

CHANGLOG.md, package.json
Hotfix for devops scripts.
Feature Emojis: 👷♂️x1
Feature Labels: [devops](https://api.github.com/repos/kids-first/kf-ui-release-coordinator/labels/devops) x1
- (#183) 👷♂️ Add agent label - @dankolbman
=> 🏷 Release 1.8.1

.circleci/config.yml, netlify.toml
Updates circle to publish to cloud front and netlify to deploy qa and dev.
=> 🔧 Update netlify and circle CI configs

CHANGELOG.md, release_maker_cfg.json
- Emojis: 🔧 x1, ⬆️ x1, 🐛 x1
- Categories: Other Changes x1, Ops x1, Fixes x1
- [#195](https://github.com/kids-first/kf-ui-release-coordinator/pull/195) - 🔧 Update netlify and circle CI configs - [806fa2c5](https://github.com/kids-first/kf-ui-release-coordinator/commit/806fa2c5f6ae5f6f1ee067c607e0d41f298cefad) by [dankolbman](https://github.com/dankolbman)
- [#190](https://github.com/kids-first/kf-ui-release-coordinator/pull/190) - ⬆️ Bump websocket-extensions from 0.1.3 to 0.1.4 - [70df4ab2](https://github.com/kids-first/kf-ui-release-coordinator/commit/70df4ab2e0e3034470946ac6b77426244847a3f1) by [dependabot[bot]](https://github.com/apps/dependabot)
- [#185](https://github.com/kids-first/kf-ui-release-coordinator/pull/185) - 🐛 Fix mm/dd/yyyy format date utility function - …
=> 🏷 Release 1.8.2

netlify.toml
Remove master context variables so as not to overwrite production variables.
=> 🐛 Remove qa environment variables

CHANGELOG.md
- Emojis: 🐛 x1
- Categories: Fixes x1
- [#197](https://github.com/kids-first/kf-ui-release-coordinator/pull/197) - 🐛 Remove qa environment variables - [f1076df7](https://github.com/kids-first/kf-ui-release-coordinator/commit/f1076df7f1e4adc0419bd46aa9790064cd647707) by [dankolbman](https://github.com/dankolbman)
=> 🏷 Release 1.8.3

netlify.toml
Builds with QA variables for all branch deploys and dev for all deploy previews.
=> 🔧 Build QA for branch deploys

netlify.toml
Hardcodes redirects for the branch deploy builds.
=> 🔧 Hardcode QA redirects for branch deploy
